version: '3.4'

services:
  weaviate:
    image: semitechnologies/weaviate:1.24.7
    command: ["--host", "0.0.0.0", "--scheme", "http", "--port", "8080"]
    ports:
      - "8080:8080"
      - "50051:50051"
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      DEFAULT_VECTORIZER_MODULE: "none"
      ENABLE_MODULES: "none"
      CLUSTER_HOSTNAME: "node1"
      ENABLE_GRPC: "true"
      GRPC_BIND_PORT: "50051"
    volumes:
      - ${WEAVIATE_HOST_VOLUME_PATH}:/var/lib/weaviate
