# version: '3.4'

services:
  weaviate:
    image: semitechnologies/weaviate:1.24.7
    env_file:
      - .env
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      #AUTHENTICATION_APIKEY_ENABLED: "true"
      #AUTHENTICATION_APIKEY_ALLOWED_KEYS: ${WEAVIATE_API_KEY}
      #AUTHENTICATION_APIKEY_ALLOWED_USERS: ${WEAVIATE_USERNAME}
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      DEFAULT_VECTORIZER_MODULE: "none"
      ENABLE_MODULES: "none"
      CLUSTER_HOSTNAME: "node1"
      GRPC_ENABLED: "true"
      GRPC_BIND_PORT: "50051"
    volumes:
      - weaviate_data:/var/lib/weaviate

volumes:
  weaviate_data:


