version: '3.4'

services:
  weaviate:
    image: semitechnologies/weaviate:1.24.7
    command: ["--host", "0.0.0.0", "--scheme", "http", "--port", "8080"]
    ports:
      - "8080:8080"
      - "50051:50051"
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      DEFAULT_VECTORIZER_MODULE: "none"
      ENABLE_MODULES: "none"
      CLUSTER_HOSTNAME: "node1"
      ENABLE_GRPC: "true"
      GRPC_BIND_PORT: "50051"
    volumes:
      # Bind-mount explícito: carpeta del host con los datos  ➜  ruta interna esperada
      - /home/consistorioai/weaviate_data:/var/lib/weaviate

# Eliminamos la declaración de volumen anónimo porque ya no se usa
# volumes:
#   weaviate_data:

# --------------------------- OPCIONAL: Volumen persistente Docker ---------------------------
# Si deseas usar un volumen persistente de Docker en lugar de un bind-mount explícito
#       - legaldocs_v2:/var/lib/weaviate  # <-- Monta el volumen Docker persistente

# volumes:
#   legaldocs_v2:
#     external: true  # <-- Indica que el volumen ya existe y no debe crearse como anónimo
